version: '2'

services:
    app:
        image: raivieiraadriano92/node-tools:latest
        environment:
            NODE_ENV: development
        volumes:
            - .:/usr/src
        working_dir: /usr/src
        ports:
            - '3000:3000'
        tty: true
        links:
            - mongodb
        depends_on:
            - mongodb

    mongodb:
        image: mongo:3.2.5
